"""Vocabulaire courant FR / EN par classe.

Aucune liste de marques ne couvrira le boucher du coin ni « clopes ». Ce sont
les mots communs qui permettent au modèle de classer ce qu'il n'a jamais vu :
c'est le seul axe qui traite la traîne infinie des commerces locaux.
"""

from typing import Iterator

from knowledge.entities import TIER_HEAD, Entity
from knowledge.sources.services import RECURRING_SLUGS
from taxonomy import ONE_TIME, RECURRING

SOURCE = "lexicon"

LEXICON: dict[str, list[str]] = {
    "alimentation.supermarche": [
        "courses", "les courses", "courses de la semaine", "provisions", "ravitaillement",
        "caddie", "chariot", "supermarché", "hypermarché", "drive", "click and collect",
        "courses en ligne", "grosses courses", "petites courses", "groceries", "grocery run",
        "grocery shopping", "food shop", "weekly shop", "supermarket", "grocery store",
        "big shop", "food shopping", "grocery delivery", "pantry restock",
    ],
    "alimentation.marche": [
        "marché", "marché du dimanche", "marché couvert", "marché bio", "primeur",
        "étal du marché", "producteur local", "AMAP", "panier de légumes", "panier bio",
        "vente à la ferme", "cueillette", "farmers market", "market stall", "veg box",
        "farm shop", "local produce", "greengrocer stall",
    ],
    "alimentation.epicerie": [
        "épicerie", "épicerie fine", "épicerie de quartier", "supérette", "boucherie",
        "charcuterie", "poissonnerie", "fromagerie", "cave à vin", "caviste", "traiteur",
        "primeurs", "magasin bio", "vrac", "torréfacteur", "chocolaterie", "confiserie",
        "corner shop", "convenience store", "butcher", "butcher's", "fishmonger",
        "cheesemonger", "off licence", "deli", "delicatessen", "wine shop", "health food shop",
        "bulk store", "grocer",
    ],
    "alimentation.boulangerie": [
        "boulangerie", "baguette", "baguettes", "deux baguettes", "pain", "pain complet",
        "pain de mie", "viennoiseries", "croissants",
        "pain au chocolat", "chocolatine", "brioche", "pâtisserie", "gâteau", "tarte",
        "éclair", "macarons", "boulange", "sandwich boulangerie", "formule boulangerie",
        "bakery", "loaf of bread", "loaf", "sourdough", "sourdough loaf", "bread", "bread roll",
        "pastries", "croissant", "bun", "cake shop",
        "patisserie", "doughnuts", "bakery run",
    ],
    "restauration.restaurant": [
        "restaurant", "resto", "restau", "dîner au restaurant", "déjeuner", "repas",
        "brasserie", "bistrot", "auberge", "table d'hôtes", "menu du midi", "formule midi",
        "addition", "note du resto", "resto avec les collègues", "resto en amoureux",
        "sushi", "pizzeria", "italien", "chinois", "japonais", "indien", "thaï", "grec",
        "libanais", "coréen", "burger resto", "steakhouse", "crêperie", "brunch",
        "dinner out", "eating out", "meal out", "lunch out", "restaurant bill", "the bill",
        "dinner with friends", "sunday roast", "tasting menu", "takeout meal",
    ],
    "restauration.fast_food": [
        "fast food", "fast-food", "burger", "hamburger", "kebab", "tacos", "pizza",
        "sandwich", "panini", "hot dog", "frites", "nuggets", "menu maxi best of",
        "wrap", "poke bowl", "bagel", "friterie", "snack", "food truck", "camion pizza",
        "bouffe rapide", "fish and chips", "chippy", "chicken shop", "takeaway",
        "drive-thru", "combo meal", "fries", "burrito", "quesadilla", "ramen bar",
    ],
    "restauration.bar": [
        "bar", "pub", "bière", "bières", "pinte", "apéro", "apéritif", "verre",
        "un verre", "cocktails", "happy hour", "boîte de nuit", "discothèque", "club",
        "tournée", "coupe de champagne", "vin au bar", "rooftop", "brasserie du coin",
        "beers", "pint", "pints", "drinks", "drinks out", "night out", "cocktail bar",
        "wine bar", "nightclub", "bar tab", "round of drinks",
    ],
    "restauration.cafe": [
        "café", "petit café", "expresso", "espresso", "cappuccino", "latte", "noisette",
        "thé", "chocolat chaud", "café croissant", "pause café", "salon de thé",
        "café en terrasse", "petit noir", "café au comptoir", "coffee", "flat white",
        "americano", "iced coffee",
        "coffee shop", "morning coffee", "tea", "hot chocolate", "matcha", "chai latte",
    ],
    "restauration.livraison": [
        "livraison", "commande à emporter", "livraison de repas", "livraison pizza",
        "livraison sushi", "commande en ligne repas", "frais de livraison repas",
        "food delivery", "delivery order", "takeaway delivered", "meal delivery",
        "delivery fee", "ordered in",
    ],
    "transport.essence": [
        "essence", "carburant", "gasoil", "gazole", "diesel", "SP95", "SP98", "E85",
        "plein", "plein d'essence", "faire le plein", "station-service", "station essence",
        "pompe", "recharge électrique", "borne de recharge", "charge voiture", "GPL",
        "fuel", "petrol", "gas", "gasoline", "filled up", "fill up", "petrol station",
        "gas station", "diesel fill", "ev charging", "charging point",
    ],
    "transport.transport_commun": [
        "métro", "bus", "tram", "tramway", "RER", "ticket de métro", "ticket de bus",
        "carnet de tickets", "abonnement transport", "pass mensuel", "carte de transport",
        "trajet bus", "navette", "trottinette en libre-service", "vélo en libre-service",
        "vélo partagé", "underground", "tube", "subway", "bus fare", "train fare",
        "travelcard", "oyster top up", "monthly pass", "transit pass", "commute",
        "e-scooter ride", "bike share",
    ],
    "transport.taxi_vtc": [
        "taxi", "VTC", "course taxi", "course VTC", "chauffeur", "voiture avec chauffeur",
        "taxi de nuit", "taxi aéroport", "cab", "ride", "rideshare", "airport taxi",
        "uber ride", "bolt ride", "airport transfer", "trajet en VTC", "retour en taxi",
        "minicab", "car service",
    ],
    "transport.parking": [
        "parking", "stationnement", "horodateur", "place de parking", "parking souterrain",
        "parking aéroport", "abonnement parking", "ticket de parking", "car park",
        "parking fee", "parking ticket", "meter", "garage parking", "monthly parking",
    ],
    "transport.peage": [
        "péage", "autoroute", "badge télépéage", "frais d'autoroute", "toll",
        "motorway toll", "tolls", "road charge", "congestion charge", "vignette autoroute",
    ],
    "transport.entretien_vehicule": [
        "garage", "révision", "vidange", "entretien voiture", "réparation voiture",
        "pneus", "changement de pneus", "plaquettes de frein", "contrôle technique",
        "carrosserie", "pare-brise", "batterie voiture", "lavage auto", "car wash",
        "mécanicien", "pièces auto", "amortisseurs", "embrayage", "courroie",
        "MOT", "service", "car service", "oil change", "tyres", "brake pads",
        "car repair", "mechanic", "bodywork", "windscreen", "car parts",
    ],
    "logement.loyer": [
        "loyer", "loyer du mois", "loyer appartement", "loyer studio", "quittance",
        "caution", "dépôt de garantie", "frais d'agence", "colocation", "part de loyer",
        "caution appartement", "caution logement", "rent", "monthly rent", "rent payment",
        "deposit", "letting fee", "room rent",
        "flatshare rent",
    ],
    "logement.charges": [
        "charges", "charges de copropriété", "charges locatives", "provision pour charges",
        "syndic", "appel de fonds", "ordures ménagères", "entretien immeuble",
        "service charge", "ground rent", "council tax", "building fees", "communal charges",
    ],
    "logement.energie": [
        "électricité", "facture électricité", "gaz", "facture de gaz", "chauffage",
        "fioul", "granulés", "pellets", "bois de chauffage", "propane", "abonnement gaz",
        "abonnement électricité", "consommation électrique", "electricity", "electric bill",
        "gas bill", "heating", "heating oil", "energy bill", "utility bill", "power bill",
    ],
    "logement.eau": [
        "eau", "facture d'eau", "consommation d'eau", "assainissement", "abonnement eau",
        "water", "water bill", "water rates", "sewerage",
    ],
    "logement.travaux": [
        "travaux", "bricolage", "peinture", "plomberie", "électricité travaux", "carrelage",
        "parquet", "isolation", "rénovation", "outillage", "quincaillerie", "visserie",
        "perceuse", "ciment", "placo", "menuiserie", "serrurier", "dépannage plombier",
        "artisan", "devis travaux", "jardinage", "terreau", "plantes", "tondeuse",
        "DIY", "home improvement", "renovation", "paint", "plumbing", "plumber",
        "electrician", "handyman", "hardware", "tools", "drill", "tiling", "flooring",
        "gardening", "garden centre",
    ],
    "sante_beaute.medecin": [
        "médecin", "docteur", "consultation", "généraliste", "spécialiste", "dentiste",
        "ophtalmo", "dermato", "gynéco", "cardiologue", "kiné", "kinésithérapeute",
        "ostéopathe", "psychologue", "psychiatre", "analyses", "laboratoire", "radio",
        "IRM", "scanner", "vaccin", "urgences", "infirmier", "prise de sang", "orthodontiste",
        "doctor", "GP", "appointment", "dentist", "optician appointment", "physio",
        "physiotherapy", "osteopath", "therapist", "therapy session", "blood test",
        "x-ray", "scan", "consultant", "clinic", "check-up", "vaccination",
    ],
    "sante_beaute.pharmacie": [
        "pharmacie", "médicaments", "ordonnance", "paracétamol", "ibuprofène", "antibiotiques",
        "sirop", "pansements", "compléments alimentaires", "vitamines", "probiotiques",
        "crème pharmacie", "test antigénique", "masques", "lentilles", "lunettes",
        "opticien", "audioprothèse", "matériel médical", "pharmacy", "chemist",
        "medicine", "meds", "prescription", "painkillers", "plasters", "supplements",
        "vitamins", "contact lenses", "glasses", "eye test", "first aid",
    ],
    "sante_beaute.coiffeur": [
        "coiffeur", "coupe de cheveux", "coupe", "brushing", "couleur", "coloration",
        "mèches", "balayage", "barbier", "taille de barbe", "shampoing coiffeur",
        "coiffeuse", "salon de coiffure", "haircut", "hair cut", "barber", "hairdresser",
        "hair salon", "blow dry", "hair colour", "highlights", "beard trim",
    ],
    "sante_beaute.esthetique": [
        "esthéticienne", "institut", "soin visage", "épilation", "cire", "manucure",
        "pédicure", "vernis", "faux ongles", "massage", "spa", "hammam", "sauna",
        "maquillage", "parfum", "crème visage", "soin corps", "cosmétiques", "beauté",
        "UV", "bronzage", "microblading", "cils", "extensions de cils", "tatouage",
        "beauty", "beautician", "facial", "waxing", "manicure", "pedicure", "nails",
        "massage session", "spa day", "make up", "perfume", "skincare", "cosmetics",
        "lashes", "tanning", "tattoo",
    ],
    "loisirs.cinema_sortie": [
        "cinéma", "ciné", "place de cinéma", "séance", "film", "théâtre", "spectacle",
        "concert", "festival", "musée", "expo", "exposition", "opéra", "comédie musicale",
        "parc d'attractions", "bowling", "escape game", "laser game", "karaoké",
        "billet spectacle", "sortie", "cinema", "movie", "movie ticket", "film night",
        "theatre", "show", "gig", "concert ticket", "festival ticket", "exhibition",
        "bowling", "escape room", "night out", "comedy show",
    ],
    "loisirs.jeux_video": [
        "jeu vidéo", "jeux vidéo", "jeu", "console", "manette", "carte cadeau jeu",
        "DLC", "skin", "V-Bucks", "abonnement jeu", "free to play", "précommande jeu",
        "extension jeu", "gaming", "video game", "game", "console game", "controller",
        "in-game purchase", "game pass", "loot box", "game key", "preorder game",
    ],
    "loisirs.sport": [
        "sport", "salle de sport", "abonnement salle", "musculation", "fitness", "yoga",
        "pilates", "natation", "piscine", "escalade", "tennis", "padel", "foot", "football",
        "basket", "running", "course à pied", "vélo", "licence sportive", "cotisation club",
        "équipement sport", "chaussures de running", "raquette", "cours collectif",
        "coach sportif", "gym", "gym membership", "workout", "swimming", "swim session",
        "climbing", "tennis court", "pitch hire", "sports gear", "trainers", "running shoes",
        "personal trainer", "club fees",
    ],
    "loisirs.livre_presse": [
        "livre", "livres", "roman", "BD", "bande dessinée", "manga", "magazine", "revue",
        "journal", "presse", "abonnement journal", "abonnement magazine", "librairie",
        "livre de poche", "livre audio", "liseuse", "book", "books", "novel", "comic",
        "magazine subscription", "newspaper", "bookshop", "paperback", "audiobook",
        "ebook", "kindle book", "press subscription",
    ],
    "loisirs.streaming": [
        "streaming", "abonnement streaming", "abonnement vidéo", "VOD", "plateforme vidéo",
        "abo streaming", "film en ligne", "série", "streaming subscription",
        "video subscription", "tv subscription", "movie rental", "streaming service",
    ],
    "loisirs.musique": [
        "musique", "abonnement musique", "streaming musical", "playlist", "album",
        "vinyle", "CD", "concert en ligne", "cours de musique", "solfège", "instrument",
        "guitare", "piano", "music subscription", "music streaming", "vinyl", "record",
        "album purchase", "music lesson", "guitar lesson",
    ],
    "numerique.logiciel_service": [
        "logiciel", "licence logiciel", "abonnement logiciel", "application", "app",
        "abonnement app", "SaaS", "outil en ligne", "suite bureautique", "antivirus",
        "VPN", "gestionnaire de mots de passe", "achat in-app", "abonnement premium",
        "software", "software licence", "app subscription", "productivity tool",
        "password manager", "in-app purchase", "premium plan", "annual plan", "pro plan",
    ],
    "numerique.ia": [
        "IA", "intelligence artificielle", "abonnement IA", "assistant IA", "chatbot",
        "crédits IA", "API IA", "génération d'images", "modèle IA", "AI", "AI subscription",
        "AI assistant", "AI credits", "API credits", "image generation", "LLM subscription",
    ],
    "numerique.hebergement_domaine": [
        "hébergement", "hébergement web", "serveur", "VPS", "nom de domaine", "domaine",
        "renouvellement domaine", "certificat SSL", "hébergeur", "cloud serveur",
        "hosting", "web hosting", "server", "domain", "domain name", "domain renewal",
        "ssl certificate", "cloud server", "dedicated server",
    ],
    "numerique.stockage_cloud": [
        "stockage cloud", "stockage en ligne", "espace de stockage", "sauvegarde en ligne",
        "backup cloud", "abonnement stockage", "cloud storage", "online storage",
        "storage plan", "cloud backup", "extra storage",
    ],
    "numerique.telecom": [
        "forfait mobile", "forfait téléphone", "abonnement mobile", "box internet",
        "internet", "fibre", "ADSL", "facture téléphone", "recharge mobile", "data",
        "roaming", "ligne fixe", "téléphone portable forfait", "mobile plan", "phone bill",
        "phone contract", "broadband", "internet bill", "wifi bill", "sim card",
        "top up", "data plan", "landline",
    ],
    "shopping.vetements": [
        "vêtements", "fringues", "habits", "pantalon", "jean", "t-shirt", "chemise",
        "pull", "manteau", "veste", "robe", "jupe", "chaussures", "baskets", "sneakers",
        "bottes", "sandales", "chaussettes", "sous-vêtements", "pyjama", "maillot de bain",
        "sac à main", "ceinture", "écharpe", "bonnet", "casquette", "bijoux", "montre",
        "lunettes de soleil", "soldes", "shopping vêtements", "retouche", "clothes",
        "clothing", "outfit", "jeans", "shirt", "jumper", "coat", "jacket", "dress",
        "shoes", "trainers", "boots", "socks", "underwear", "swimwear", "handbag",
        "belt", "scarf", "hat", "jewellery", "watch", "sunglasses", "sale shopping",
    ],
    "shopping.electronique": [
        "électronique", "téléphone", "smartphone", "portable", "ordinateur", "PC",
        "laptop", "tablette", "écran", "clavier", "souris", "casque", "écouteurs",
        "enceinte", "TV", "télévision", "imprimante", "disque dur", "clé USB", "chargeur",
        "câble", "batterie externe", "montre connectée", "appareil photo", "drone",
        "console de jeu", "électroménager", "aspirateur", "cafetière", "micro-ondes",
        "lave-linge", "frigo", "electronics", "phone", "laptop", "computer", "tablet",
        "monitor", "keyboard", "mouse", "headphones", "earbuds", "speaker", "tv",
        "printer", "hard drive", "usb stick", "charger", "cable", "power bank",
        "smartwatch", "camera", "appliance", "vacuum", "kettle", "microwave",
        "washing machine", "fridge",
    ],
    "shopping.mobilier_deco": [
        "meuble", "meubles", "canapé", "fauteuil", "table", "chaise", "lit", "matelas",
        "armoire", "étagère", "bureau meuble", "commode", "tapis", "rideaux", "coussin",
        "lampe", "luminaire", "miroir", "cadre photo", "déco", "décoration", "vaisselle",
        "assiettes", "verres", "casseroles", "linge de maison", "draps", "serviettes",
        "plantes déco", "bougie", "furniture", "sofa", "armchair", "table", "chair",
        "bed", "mattress", "wardrobe", "shelf", "desk", "rug", "curtains", "cushion",
        "lamp", "mirror", "picture frame", "home decor", "crockery", "plates", "glasses",
        "pans", "bedding", "towels", "candle",
    ],
    "finance.retrait_dab": [
        "retrait", "retrait DAB", "retrait distributeur", "distributeur", "cash",
        "liquide", "espèces", "retrait espèces", "argent liquide", "retrait au guichet",
        "cash withdrawal", "atm", "atm withdrawal", "cash out", "cashpoint", "withdrew cash",
    ],
    "finance.frais_bancaires": [
        "frais bancaires", "frais de tenue de compte", "cotisation carte bancaire",
        "agios", "commission d'intervention", "frais de découvert", "frais virement",
        "frais à l'étranger", "frais de change", "commission", "bank fees", "account fee",
        "card fee", "overdraft fee", "transaction fee", "foreign exchange fee",
        "transfer fee", "monthly banking fee",
    ],
    "finance.impots_taxes": [
        "impôts", "impôt", "taxe", "taxes", "taxe foncière", "taxe d'habitation",
        "impôt sur le revenu", "prélèvement à la source", "TVA", "cotisations sociales",
        "URSSAF", "redevance", "acompte impôt", "tiers provisionnel", "tax", "taxes",
        "income tax", "council tax", "property tax", "vat", "national insurance",
        "self assessment", "tax payment", "tax bill",
    ],
    "finance.amende": [
        "amende", "PV", "contravention", "prune", "amende stationnement", "amende vitesse",
        "amende SNCF", "amende métro", "majoration amende", "fine", "parking fine",
        "speeding fine", "penalty", "penalty charge", "late payment fee", "ticket fine",
    ],
    "finance.assurance_habitation": [
        "assurance habitation", "assurance logement", "assurance appartement",
        "assurance maison", "multirisque habitation", "MRH", "assurance locataire",
        "home insurance", "contents insurance", "buildings insurance", "renters insurance",
        "flat insurance",
    ],
    "finance.assurance_auto": [
        "assurance auto", "assurance voiture", "assurance véhicule", "assurance moto",
        "assurance scooter", "prime d'assurance auto", "cotisation assurance auto",
        "car insurance", "motor insurance", "van insurance", "bike insurance",
        "vehicle cover", "third party insurance",
    ],
    "finance.assurance_sante": [
        "mutuelle", "complémentaire santé", "assurance santé", "cotisation mutuelle",
        "assurance dentaire", "prévoyance", "health insurance", "medical insurance",
        "dental cover", "private health cover", "health plan",
    ],
    "finance.epargne_investissement": [
        "épargne", "virement épargne", "livret", "livret A", "PEL", "PEA", "assurance vie",
        "bourse", "actions", "ETF", "obligations", "crypto", "bitcoin", "placement",
        "investissement", "versement épargne", "savings", "saving", "investment",
        "stocks", "shares", "index fund", "crypto", "pension contribution", "isa",
        "put aside", "transfer to savings",
    ],
    "finance.credit_pret": [
        "crédit", "prêt", "mensualité", "échéance de prêt", "remboursement crédit",
        "crédit conso", "crédit auto", "prêt immobilier", "prêt étudiant", "découvert",
        "paiement en plusieurs fois", "3x sans frais", "loan", "loan repayment",
        "mortgage", "mortgage payment", "car loan", "student loan", "credit card payment",
        "instalment", "buy now pay later", "repayment",
    ],
    "famille_education.scolarite": [
        "scolarité", "frais de scolarité", "inscription école", "rentrée scolaire",
        "école privée", "collège", "lycée", "université", "fac", "internat",
        "voyage scolaire", "sortie scolaire", "assurance scolaire", "school fees",
        "tuition", "tuition fees", "enrolment", "term fees", "school trip", "uni fees",
    ],
    "famille_education.fournitures": [
        "fournitures scolaires", "cartable", "cahiers", "stylos", "trousse", "classeur",
        "calculatrice", "manuels scolaires", "livres scolaires", "papeterie", "agenda",
        "sac à dos école", "school supplies", "stationery", "notebooks", "pens",
        "backpack", "calculator", "textbooks", "school uniform",
    ],
    "famille_education.formation": [
        "formation", "cours", "cours en ligne", "cours du soir", "stage de formation",
        "certification", "diplôme", "auto-école", "permis de conduire", "code de la route",
        "cours particuliers", "soutien scolaire", "cours de langue", "MOOC", "atelier",
        "training", "course", "online course", "evening class", "workshop", "bootcamp",
        "driving lessons", "driving test", "language course", "tutoring", "private lessons",
    ],
    "famille_education.garde_enfant": [
        "garde d'enfant", "nounou", "assistante maternelle", "crèche", "halte-garderie",
        "baby-sitter", "babysitting", "périscolaire", "garderie", "centre aéré",
        "childcare", "nursery", "childminder", "babysitter", "nanny", "after school club",
        "holiday club", "creche",
    ],
    "famille_education.cantine": [
        "cantine", "cantine scolaire", "self", "restauration scolaire", "ticket cantine",
        "repas école", "panier repas", "school meals", "school lunch", "dinner money",
        "lunch card", "canteen",
    ],
    "famille_education.activites_enfants": [
        "activités enfants", "jouets", "jeux enfants", "peluche", "poupée", "lego",
        "activité extrascolaire", "cours de danse", "cours de judo", "école de musique",
        "poterie enfant", "anniversaire enfant", "parc de jeux", "trampoline park",
        "kids activities", "toys", "toy", "soft toy", "kids club", "dance class",
        "swimming lessons", "music lessons", "birthday party", "play centre",
    ],
    "famille_education.pension_alimentaire": [
        "pension alimentaire", "contribution éducation", "versement pension",
        "aide aux parents", "aide à mon fils", "aide à ma fille", "child support",
        "child maintenance", "maintenance payment", "alimony", "family support payment",
    ],
    "voyage.transport_longue_distance": [
        "billet de train", "billet d'avion", "avion", "vol", "train", "TGV", "car",
        "bus longue distance", "covoiturage", "ferry", "bateau", "aller-retour",
        "aller simple", "bagage en soute", "supplément bagage", "réservation vol",
        "flight", "plane ticket", "train ticket", "coach ticket", "ferry ticket",
        "return ticket", "one way", "checked bag", "seat selection", "rail fare",
    ],
    "voyage.hebergement": [
        "hôtel", "nuit d'hôtel", "auberge de jeunesse", "airbnb", "gîte", "chambre d'hôtes",
        "camping", "emplacement camping", "location vacances", "résidence de vacances",
        "réservation hôtel", "hotel", "hotel night", "hostel", "guest house", "bnb",
        "holiday rental", "campsite", "accommodation", "booking",
    ],
    "voyage.location_vehicule": [
        "location de voiture", "location véhicule", "location utilitaire",
        "location camion", "location scooter", "location vélo", "caution location voiture",
        "car hire", "car rental", "van hire", "rental car", "scooter hire", "bike hire",
    ],
    "voyage.activite_visite": [
        "visite", "entrée musée", "billet monument", "visite guidée", "excursion",
        "activité vacances", "parc national", "croisière", "plongée", "ski", "forfait ski",
        "location ski", "randonnée guidée", "attraction", "guided tour", "day trip",
        "excursion", "museum entry", "attraction ticket", "ski pass", "lift pass",
        "forfait ski", "forfait remontées", "entrée musée", "entrée château", "billet musée",
        "boat trip", "sightseeing",
    ],
    "divers.cadeau_offert": [
        "cadeau", "cadeaux", "cadeau anniversaire", "cadeau de Noël", "cadeau mariage",
        "cadeau naissance", "carte cadeau", "chèque cadeau", "fleurs offertes",
        "présent", "gift", "present", "birthday gift", "christmas present", "wedding gift",
        "gift card", "flowers for", "secret santa",
    ],
    "divers.animaux": [
        "vétérinaire", "véto", "croquettes", "nourriture chien", "nourriture chat",
        "litière", "toilettage", "animalerie", "vaccin animal", "vermifuge", "anti-puces",
        "laisse", "collier chien", "jouet chat", "aquarium", "cage", "foin", "pension animalière",
        "vet", "vet bill", "pet food", "dog food", "cat food", "cat litter", "grooming",
        "pet shop", "flea treatment", "pet insurance", "kennels", "cattery", "dog walker",
    ],
    "divers.tabac_jeux": [
        "tabac", "clopes", "cigarettes", "paquet de clopes", "cartouche", "briquet",
        "e-cigarette", "vapoteuse", "e-liquide", "puff", "cigare", "chicha",
        "loto", "grattage", "jeu à gratter", "pari sportif", "paris sportifs", "PMU",
        "casino", "poker", "mise", "bureau de tabac", "buraliste", "tobacco",
        "cigarettes", "pack of cigarettes", "vape", "vape juice", "lighter",
        "lottery", "lottery ticket", "scratch card", "bet", "sports bet", "betting",
        "casino night", "poker night",
    ],
    "divers.don": [
        "don", "dons", "donation", "don association", "don mensuel", "cotisation association",
        "collecte", "cagnotte", "soutien", "mécénat", "offrande", "charité",
        "charity", "charity donation", "monthly donation", "fundraiser", "sponsorship",
        "giving", "tithe", "crowdfunding",
    ],
    "divers.autre": [
        "divers", "autre", "dépense diverse", "imprévu", "frais divers", "pressing",
        "laverie", "cordonnier", "photocopies", "timbres", "colis", "envoi", "poste",
        "déménagement", "garde-meuble", "serrurier urgence", "photographe", "notaire",
        "avocat", "clé", "miscellaneous", "other", "dry cleaning", "laundrette",
        "shoe repair", "photocopies", "stamps", "parcel", "postage", "moving",
        "storage unit", "locksmith", "photographer", "solicitor", "notary",
    ],
    "salaire.salaire_net": [
        "salaire", "paye", "paie", "salaire net", "salaire du mois", "virement salaire",
        "fiche de paie", "bulletin de salaire", "net à payer", "rémunération",
        "traitement", "solde de tout compte", "salary", "wage", "wages", "pay",
        "payday", "monthly salary", "paycheck", "payslip", "net pay", "take home pay",
    ],
    "salaire.prime": [
        "prime", "bonus", "prime annuelle", "prime de fin d'année", "13ème mois",
        "intéressement", "participation", "prime exceptionnelle", "prime de vacances",
        "commission vente", "pourboire", "pourboires", "bonus payment", "annual bonus",
        "commission", "tips", "overtime pay", "performance bonus",
    ],
    "salaire.freelance": [
        "freelance", "mission freelance", "facture client", "honoraires", "prestation",
        "acompte client", "auto-entrepreneur", "revenu indépendant", "consulting",
        "freelance payment", "client payment", "invoice paid", "contract work",
        "side hustle", "gig income",
    ],
    "salaire.retraite": [
        "retraite", "pension", "pension de retraite", "retraite complémentaire",
        "versement retraite", "pension", "state pension", "retirement income",
        "pension payment", "private pension",
    ],
    "aide_allocation.allocation_familiale": [
        "allocations familiales", "allocation familiale", "CAF", "prime de naissance",
        "complément familial", "allocation de rentrée scolaire", "child benefit",
        "family allowance", "child tax credit",
    ],
    "aide_allocation.chomage": [
        "chômage", "allocation chômage", "indemnités chômage", "ARE", "France Travail",
        "Pôle emploi", "unemployment benefit", "jobseeker's allowance", "universal credit",
        "dole",
    ],
    "aide_allocation.aide_logement": [
        "APL", "aide au logement", "allocation logement", "aide personnalisée au logement",
        "housing benefit", "housing allowance", "rent support",
    ],
    "aide_allocation.bourse": [
        "bourse", "bourse d'études", "bourse CROUS", "bourse au mérite", "aide étudiante",
        "student grant", "scholarship", "bursary", "student finance", "maintenance grant",
    ],
    "transfert.virement_recu": [
        "virement reçu", "virement", "transfert reçu", "argent reçu", "versement reçu",
        "reçu de la banque", "transfert entre comptes", "transfer received",
        "money received", "incoming transfer", "bank transfer in", "deposit",
    ],
    "transfert.remboursement_sante": [
        "remboursement santé", "remboursement mutuelle", "remboursement sécu",
        "remboursement CPAM", "remboursement médecin", "remboursement pharmacie",
        "health refund", "insurance refund", "medical reimbursement", "nhs refund",
    ],
    "transfert.remboursement_ami": [
        "remboursement", "remboursement pote", "remboursé par", "m'a remboursé",
        "part du resto", "part du cadeau", "cagnotte remboursée", "note partagée",
        "paid me back", "reimbursed by", "split the bill", "share of dinner",
        "money back from friend", "settled up",
    ],
    "transfert.remboursement_impots": [
        "remboursement impôts", "trop-perçu", "crédit d'impôt", "restitution impôt",
        "tax refund", "tax rebate", "overpaid tax back",
    ],
    "exceptionnel.vente_occasion": [
        "vente", "vendu", "vente occasion", "revente", "vide-grenier", "brocante",
        "vendu en ligne", "vendu sur internet", "vente de meuble", "vente de vêtements",
        "sold", "sold online", "second hand sale", "car boot sale", "resale", "flipped",
    ],
    "exceptionnel.don_recu": [
        "don reçu", "cadeau reçu", "argent de mes parents", "enveloppe reçue",
        "étrennes", "cadeau d'anniversaire reçu", "gift received", "money from parents",
        "birthday money", "cash gift",
    ],
    "exceptionnel.interets": [
        "intérêts", "intérêts livret", "intérêts épargne", "dividendes", "coupons",
        "plus-value", "cashback", "rendement", "interest", "savings interest",
        "dividends", "capital gain", "cashback received", "yield",
    ],
    "exceptionnel.loyer_percu": [
        "loyer perçu", "loyer reçu", "revenus locatifs", "loyer locataire",
        "revenu Airbnb", "rental income", "rent received", "tenant payment",
        "letting income",
    ],
}


def iter_entities() -> Iterator[Entity]:
    for slug, terms in LEXICON.items():
        recurrence = RECURRING if slug in RECURRING_SLUGS else ONE_TIME
        for term in terms:
            yield Entity(
                name=term,
                slug=slug,
                source=SOURCE,
                tier=TIER_HEAD,
                recurrence=recurrence,
            )
