// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/account_model.dart';
import 'models/beneficiary_model.dart';
import 'models/category_memory_model.dart';
import 'models/category_override_model.dart';
import 'models/expense_model.dart';
import 'models/legacy_category_model.dart';
import 'models/loan_event_model.dart';
import 'models/loan_model.dart';
import 'models/revenue_model.dart';
import 'models/transaction_event_model.dart';
import 'models/transfer_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5409636033012054049),
    name: 'AccountModel',
    lastPropertyId: const obx_int.IdUid(3, 8108667115683580211),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8880387107288098797),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1374454396313032353),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 6911216159507346562),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8108667115683580211),
        name: 'bank',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 637957068368109063),
    name: 'LegacyCategoryModel',
    lastPropertyId: const obx_int.IdUid(4, 6632633250043774965),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4274885399649890297),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6079627583281643679),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 2810518327203723333),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2964126038854478579),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6632633250043774965),
        name: 'color',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1032015678209972615),
    name: 'ExpenseModel',
    lastPropertyId: const obx_int.IdUid(12, 8351109485124106539),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5234756340208447805),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8782177432325581071),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 6881701850497049454),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 197846412074687742),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6567315342602454646),
        name: 'legacyCategoryId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7133072174613285923),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7344930449792724154),
        name: 'frequency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4626612722441888507),
        name: 'accountId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1483699693588998820),
        name: 'beneficiaryId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 991309912139452805),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8679329461354819461),
        name: 'parentId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2441240728905768112),
        name: 'receiptPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8351109485124106539),
        name: 'categorySlug',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 2090751105594956392),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8471750721460440152),
    name: 'LoanModel',
    lastPropertyId: const obx_int.IdUid(24, 7358679212004947045),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4357997451877774757),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8082422302266592395),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1133056242518733964),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6672806474502141075),
        name: 'lenderName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6021243847321742199),
        name: 'dayOfMonth',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4746855994874418532),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 554819563813483883),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8068317565478007606),
        name: 'accountId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2010142483118272076),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6774604440405766602),
        name: 'interestRate',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3338998208392848667),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 602772844799010819),
        name: 'insuranceValue',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6813580747910956692),
        name: 'insuranceTypeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1000548223484842297),
        name: 'repaymentTypeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 5314363640482365634),
        name: 'deferredMonths',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 5643985183887639942),
        name: 'insuranceCalculationModeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 8138263455102980410),
        name: 'immediateFirstPayment',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 7721257363888305302),
        name: 'deferralTypeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 4718741685436176634),
        name: 'fees',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 4691006289725929516),
        name: 'hasIndemnityClause',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 7358679212004947045),
        name: 'purposeId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3358114112895883942),
    name: 'RevenueModel',
    lastPropertyId: const obx_int.IdUid(11, 3735809197028549779),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 283227371286293118),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7226995627464060847),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 3572496844486688498),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3937663112501782454),
        name: 'accountId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6346179344971325834),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1213904468792118615),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 26869245949429952),
        name: 'beneficiaryId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4136998757007608198),
        name: 'frequency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5983993472411267525),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1302652480411191202),
        name: 'parentId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3735809197028549779),
        name: 'categorySlug',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 8794940862762798163),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 460490983667112828),
    name: 'BeneficiaryModel',
    lastPropertyId: const obx_int.IdUid(3, 4835571805174399151),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 908053836556984088),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7223976306336406369),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 4333406268692751455),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4835571805174399151),
        name: 'color',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 5565231467975372089),
    name: 'TransferModel',
    lastPropertyId: const obx_int.IdUid(9, 6105961692625589395),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6521738019922843589),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4962336831081318855),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 7186843688021626475),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 332212276956066665),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8859810807091112752),
        name: 'fromAccountId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7671426221682866192),
        name: 'toAccountId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1221948770519669890),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1264700332632094752),
        name: 'frequency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1834230757139125615),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6105961692625589395),
        name: 'parentId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 1277046985070582395),
    name: 'CategoryOverrideModel',
    lastPropertyId: const obx_int.IdUid(5, 4682048336154088821),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5688174198000870451),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5708900184039906668),
        name: 'slug',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(7, 4629863051053178780),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1557880881204254762),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4700457419444168703),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4682048336154088821),
        name: 'color',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 2229829926542213902),
    name: 'CategoryMemoryModel',
    lastPropertyId: const obx_int.IdUid(6, 1978380619418795510),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5493594461019541539),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4224412798548071027),
        name: 'key',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(9, 561605749385287942),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5093755349444568856),
        name: 'slug',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1414969593431498966),
        name: 'corrections',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 572874301802069433),
        name: 'useMemory',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1978380619418795510),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 5282442622348339601),
    name: 'LoanEventModel',
    lastPropertyId: const obx_int.IdUid(7, 1934536084928006596),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5779609905562893032),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1080423716192276736),
        name: 'loanId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7412238931454290300),
        name: 'typeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5726242782845823416),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5704553025308414740),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3185289945794771063),
        name: 'reamortizationModeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1934536084928006596),
        name: 'exemptionId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 7981549147354617825),
    name: 'TransactionEventModel',
    lastPropertyId: const obx_int.IdUid(7, 2300762050684801568),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5621941304765792308),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7769571246329802436),
        name: 'rootId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(11, 8271769439371245867),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6708190324143525288),
        name: 'transactionType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 907520306410394687),
        name: 'change',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3510274508242355065),
        name: 'previousValue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5459888584421500536),
        name: 'nextValue',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2300762050684801568),
        name: 'at',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(11, 7981549147354617825),
    lastIndexId: const obx_int.IdUid(11, 8271769439371245867),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      3745183620062731729,
      2052082936511433960,
      5939978804947497821,
      2223950211617359170,
      342834846661396669,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AccountModel: obx_int.EntityDefinition<AccountModel>(
      model: _entities[0],
      toOneRelations: (AccountModel object) => [],
      toManyRelations: (AccountModel object) => {},
      getId: (AccountModel object) => object.id,
      setId: (AccountModel object, int id) {
        object.id = id;
      },
      objectToFB: (AccountModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final bankOffset = fbb.writeString(object.bank);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, bankOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AccountModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '')
          ..bank = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');

        return object;
      },
    ),
    LegacyCategoryModel: obx_int.EntityDefinition<LegacyCategoryModel>(
      model: _entities[1],
      toOneRelations: (LegacyCategoryModel object) => [],
      toManyRelations: (LegacyCategoryModel object) => {},
      getId: (LegacyCategoryModel object) => object.id,
      setId: (LegacyCategoryModel object, int id) {
        object.id = id;
      },
      objectToFB: (LegacyCategoryModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final iconOffset = fbb.writeString(object.icon);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, iconOffset);
        fbb.addInt64(3, object.color);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = LegacyCategoryModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '')
          ..icon = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '')
          ..color = const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);

        return object;
      },
    ),
    ExpenseModel: obx_int.EntityDefinition<ExpenseModel>(
      model: _entities[2],
      toOneRelations: (ExpenseModel object) => [],
      toManyRelations: (ExpenseModel object) => {},
      getId: (ExpenseModel object) => object.id,
      setId: (ExpenseModel object, int id) {
        object.id = id;
      },
      objectToFB: (ExpenseModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final frequencyOffset = fbb.writeString(object.frequency);
        final receiptPathOffset = object.receiptPath == null
            ? null
            : fbb.writeString(object.receiptPath!);
        final categorySlugOffset = object.categorySlug == null
            ? null
            : fbb.writeString(object.categorySlug!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addInt64(3, object.legacyCategoryId);
        fbb.addInt64(4, object.startDate.millisecondsSinceEpoch);
        fbb.addOffset(5, frequencyOffset);
        fbb.addInt64(6, object.accountId);
        fbb.addInt64(7, object.beneficiaryId);
        fbb.addInt64(8, object.endDate?.millisecondsSinceEpoch);
        fbb.addInt64(9, object.parentId);
        fbb.addOffset(10, receiptPathOffset);
        fbb.addOffset(11, categorySlugOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final object = ExpenseModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '')
          ..amount = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..legacyCategoryId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            10,
          )
          ..startDate = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..frequency = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '')
          ..accountId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..beneficiaryId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            18,
          )
          ..endDate = endDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(endDateValue)
          ..parentId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            22,
          )
          ..receiptPath = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24)
          ..categorySlug = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 26);

        return object;
      },
    ),
    LoanModel: obx_int.EntityDefinition<LoanModel>(
      model: _entities[3],
      toOneRelations: (LoanModel object) => [],
      toManyRelations: (LoanModel object) => {},
      getId: (LoanModel object) => object.id,
      setId: (LoanModel object, int id) {
        object.id = id;
      },
      objectToFB: (LoanModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final lenderNameOffset = fbb.writeString(object.lenderName);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final insuranceTypeIdOffset = fbb.writeString(object.insuranceTypeId);
        final repaymentTypeIdOffset = fbb.writeString(object.repaymentTypeId);
        final insuranceCalculationModeIdOffset = fbb.writeString(
          object.insuranceCalculationModeId,
        );
        final deferralTypeIdOffset = fbb.writeString(object.deferralTypeId);
        final purposeIdOffset = fbb.writeString(object.purposeId);
        fbb.startTable(25);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(3, lenderNameOffset);
        fbb.addInt64(4, object.dayOfMonth);
        fbb.addInt64(5, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(6, object.endDate.millisecondsSinceEpoch);
        fbb.addInt64(8, object.accountId);
        fbb.addOffset(9, notesOffset);
        fbb.addFloat64(10, object.interestRate);
        fbb.addInt64(11, object.duration);
        fbb.addFloat64(13, object.insuranceValue);
        fbb.addOffset(14, insuranceTypeIdOffset);
        fbb.addOffset(15, repaymentTypeIdOffset);
        fbb.addInt64(16, object.deferredMonths);
        fbb.addOffset(17, insuranceCalculationModeIdOffset);
        fbb.addBool(18, object.immediateFirstPayment);
        fbb.addOffset(19, deferralTypeIdOffset);
        fbb.addFloat64(20, object.fees);
        fbb.addBool(22, object.hasIndemnityClause);
        fbb.addOffset(23, purposeIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final lenderNameParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 10, '');
        final accountIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final dayOfMonthParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final startDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final endDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final interestRateParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final durationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final repaymentTypeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final deferredMonthsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final insuranceTypeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final insuranceValueParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final insuranceCalculationModeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final immediateFirstPaymentParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          40,
          false,
        );
        final deferralTypeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 42, '');
        final feesParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        final purposeIdParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 50, '');
        final hasIndemnityClauseParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          48,
          false,
        );
        final notesParam = const fb.StringReader(asciiOptimization: true)
            .vTableGetNullable(buffer, rootOffset, 22);
        final object = LoanModel(
          id: idParam,
          name: nameParam,
          amount: amountParam,
          lenderName: lenderNameParam,
          accountId: accountIdParam,
          dayOfMonth: dayOfMonthParam,
          startDate: startDateParam,
          endDate: endDateParam,
          interestRate: interestRateParam,
          duration: durationParam,
          repaymentTypeId: repaymentTypeIdParam,
          deferredMonths: deferredMonthsParam,
          insuranceTypeId: insuranceTypeIdParam,
          insuranceValue: insuranceValueParam,
          insuranceCalculationModeId: insuranceCalculationModeIdParam,
          immediateFirstPayment: immediateFirstPaymentParam,
          deferralTypeId: deferralTypeIdParam,
          fees: feesParam,
          purposeId: purposeIdParam,
          hasIndemnityClause: hasIndemnityClauseParam,
          notes: notesParam,
        );

        return object;
      },
    ),
    RevenueModel: obx_int.EntityDefinition<RevenueModel>(
      model: _entities[4],
      toOneRelations: (RevenueModel object) => [],
      toManyRelations: (RevenueModel object) => {},
      getId: (RevenueModel object) => object.id,
      setId: (RevenueModel object, int id) {
        object.id = id;
      },
      objectToFB: (RevenueModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final frequencyOffset = fbb.writeString(object.frequency);
        final categorySlugOffset = object.categorySlug == null
            ? null
            : fbb.writeString(object.categorySlug!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.accountId);
        fbb.addFloat64(3, object.amount);
        fbb.addInt64(5, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(6, object.beneficiaryId);
        fbb.addOffset(7, frequencyOffset);
        fbb.addInt64(8, object.endDate?.millisecondsSinceEpoch);
        fbb.addInt64(9, object.parentId);
        fbb.addOffset(10, categorySlugOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final object = RevenueModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '')
          ..accountId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..amount = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..startDate = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          )
          ..beneficiaryId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            16,
          )
          ..frequency = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '')
          ..endDate = endDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(endDateValue)
          ..parentId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            22,
          )
          ..categorySlug = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);

        return object;
      },
    ),
    BeneficiaryModel: obx_int.EntityDefinition<BeneficiaryModel>(
      model: _entities[5],
      toOneRelations: (BeneficiaryModel object) => [],
      toManyRelations: (BeneficiaryModel object) => {},
      getId: (BeneficiaryModel object) => object.id,
      setId: (BeneficiaryModel object, int id) {
        object.id = id;
      },
      objectToFB: (BeneficiaryModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.color);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = BeneficiaryModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '')
          ..color = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);

        return object;
      },
    ),
    TransferModel: obx_int.EntityDefinition<TransferModel>(
      model: _entities[6],
      toOneRelations: (TransferModel object) => [],
      toManyRelations: (TransferModel object) => {},
      getId: (TransferModel object) => object.id,
      setId: (TransferModel object, int id) {
        object.id = id;
      },
      objectToFB: (TransferModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final frequencyOffset = fbb.writeString(object.frequency);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addInt64(3, object.fromAccountId);
        fbb.addInt64(4, object.toAccountId);
        fbb.addInt64(5, object.startDate.millisecondsSinceEpoch);
        fbb.addOffset(6, frequencyOffset);
        fbb.addInt64(7, object.endDate?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.parentId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final endDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = TransferModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '')
          ..amount = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..fromAccountId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..toAccountId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..startDate = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          )
          ..frequency = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '')
          ..endDate = endDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(endDateValue)
          ..parentId = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            20,
          );

        return object;
      },
    ),
    CategoryOverrideModel: obx_int.EntityDefinition<CategoryOverrideModel>(
      model: _entities[7],
      toOneRelations: (CategoryOverrideModel object) => [],
      toManyRelations: (CategoryOverrideModel object) => {},
      getId: (CategoryOverrideModel object) => object.id,
      setId: (CategoryOverrideModel object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryOverrideModel object, fb.Builder fbb) {
        final slugOffset = fbb.writeString(object.slug);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final iconOffset = object.icon == null
            ? null
            : fbb.writeString(object.icon!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, slugOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, iconOffset);
        fbb.addInt64(4, object.color);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CategoryOverrideModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..slug = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8)
          ..icon = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10)
          ..color = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            12,
          );

        return object;
      },
    ),
    CategoryMemoryModel: obx_int.EntityDefinition<CategoryMemoryModel>(
      model: _entities[8],
      toOneRelations: (CategoryMemoryModel object) => [],
      toManyRelations: (CategoryMemoryModel object) => {},
      getId: (CategoryMemoryModel object) => object.id,
      setId: (CategoryMemoryModel object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryMemoryModel object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final slugOffset = fbb.writeString(object.slug);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, slugOffset);
        fbb.addInt64(3, object.corrections);
        fbb.addBool(4, object.useMemory);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CategoryMemoryModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..key = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '')
          ..slug = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '')
          ..corrections = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..useMemory = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            12,
            false,
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          );

        return object;
      },
    ),
    LoanEventModel: obx_int.EntityDefinition<LoanEventModel>(
      model: _entities[9],
      toOneRelations: (LoanEventModel object) => [],
      toManyRelations: (LoanEventModel object) => {},
      getId: (LoanEventModel object) => object.id,
      setId: (LoanEventModel object, int id) {
        object.id = id;
      },
      objectToFB: (LoanEventModel object, fb.Builder fbb) {
        final typeIdOffset = fbb.writeString(object.typeId);
        final reamortizationModeIdOffset = fbb.writeString(
          object.reamortizationModeId,
        );
        final exemptionIdOffset = fbb.writeString(object.exemptionId);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.loanId);
        fbb.addOffset(2, typeIdOffset);
        fbb.addInt64(3, object.date.millisecondsSinceEpoch);
        fbb.addFloat64(4, object.amount);
        fbb.addOffset(5, reamortizationModeIdOffset);
        fbb.addOffset(6, exemptionIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final loanIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final typeIdParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 8, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final reamortizationModeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final exemptionIdParam = const fb.StringReader(asciiOptimization: true)
            .vTableGet(buffer, rootOffset, 16, '');
        final object = LoanEventModel(
          id: idParam,
          loanId: loanIdParam,
          date: dateParam,
          typeId: typeIdParam,
          amount: amountParam,
          reamortizationModeId: reamortizationModeIdParam,
          exemptionId: exemptionIdParam,
        );

        return object;
      },
    ),
    TransactionEventModel: obx_int.EntityDefinition<TransactionEventModel>(
      model: _entities[10],
      toOneRelations: (TransactionEventModel object) => [],
      toManyRelations: (TransactionEventModel object) => {},
      getId: (TransactionEventModel object) => object.id,
      setId: (TransactionEventModel object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionEventModel object, fb.Builder fbb) {
        final transactionTypeOffset = fbb.writeString(object.transactionType);
        final changeOffset = fbb.writeString(object.change);
        final previousValueOffset = object.previousValue == null
            ? null
            : fbb.writeString(object.previousValue!);
        final nextValueOffset = object.nextValue == null
            ? null
            : fbb.writeString(object.nextValue!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.rootId);
        fbb.addOffset(2, transactionTypeOffset);
        fbb.addOffset(3, changeOffset);
        fbb.addOffset(4, previousValueOffset);
        fbb.addOffset(5, nextValueOffset);
        fbb.addInt64(6, object.at.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = TransactionEventModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..rootId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0)
          ..transactionType = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '')
          ..change = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '')
          ..previousValue = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12)
          ..nextValue = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14)
          ..at = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AccountModel] entity fields to define ObjectBox queries.
class AccountModel_ {
  /// See [AccountModel.id].
  static final id = obx.QueryIntegerProperty<AccountModel>(
    _entities[0].properties[0],
  );

  /// See [AccountModel.name].
  static final name = obx.QueryStringProperty<AccountModel>(
    _entities[0].properties[1],
  );

  /// See [AccountModel.bank].
  static final bank = obx.QueryStringProperty<AccountModel>(
    _entities[0].properties[2],
  );
}

/// [LegacyCategoryModel] entity fields to define ObjectBox queries.
class LegacyCategoryModel_ {
  /// See [LegacyCategoryModel.id].
  static final id = obx.QueryIntegerProperty<LegacyCategoryModel>(
    _entities[1].properties[0],
  );

  /// See [LegacyCategoryModel.name].
  static final name = obx.QueryStringProperty<LegacyCategoryModel>(
    _entities[1].properties[1],
  );

  /// See [LegacyCategoryModel.icon].
  static final icon = obx.QueryStringProperty<LegacyCategoryModel>(
    _entities[1].properties[2],
  );

  /// See [LegacyCategoryModel.color].
  static final color = obx.QueryIntegerProperty<LegacyCategoryModel>(
    _entities[1].properties[3],
  );
}

/// [ExpenseModel] entity fields to define ObjectBox queries.
class ExpenseModel_ {
  /// See [ExpenseModel.id].
  static final id = obx.QueryIntegerProperty<ExpenseModel>(
    _entities[2].properties[0],
  );

  /// See [ExpenseModel.name].
  static final name = obx.QueryStringProperty<ExpenseModel>(
    _entities[2].properties[1],
  );

  /// See [ExpenseModel.amount].
  static final amount = obx.QueryDoubleProperty<ExpenseModel>(
    _entities[2].properties[2],
  );

  /// See [ExpenseModel.legacyCategoryId].
  static final legacyCategoryId = obx.QueryIntegerProperty<ExpenseModel>(
    _entities[2].properties[3],
  );

  /// See [ExpenseModel.startDate].
  static final startDate = obx.QueryDateProperty<ExpenseModel>(
    _entities[2].properties[4],
  );

  /// See [ExpenseModel.frequency].
  static final frequency = obx.QueryStringProperty<ExpenseModel>(
    _entities[2].properties[5],
  );

  /// See [ExpenseModel.accountId].
  static final accountId = obx.QueryIntegerProperty<ExpenseModel>(
    _entities[2].properties[6],
  );

  /// See [ExpenseModel.beneficiaryId].
  static final beneficiaryId = obx.QueryIntegerProperty<ExpenseModel>(
    _entities[2].properties[7],
  );

  /// See [ExpenseModel.endDate].
  static final endDate = obx.QueryDateProperty<ExpenseModel>(
    _entities[2].properties[8],
  );

  /// See [ExpenseModel.parentId].
  static final parentId = obx.QueryIntegerProperty<ExpenseModel>(
    _entities[2].properties[9],
  );

  /// See [ExpenseModel.receiptPath].
  static final receiptPath = obx.QueryStringProperty<ExpenseModel>(
    _entities[2].properties[10],
  );

  /// See [ExpenseModel.categorySlug].
  static final categorySlug = obx.QueryStringProperty<ExpenseModel>(
    _entities[2].properties[11],
  );
}

/// [LoanModel] entity fields to define ObjectBox queries.
class LoanModel_ {
  /// See [LoanModel.id].
  static final id = obx.QueryIntegerProperty<LoanModel>(
    _entities[3].properties[0],
  );

  /// See [LoanModel.name].
  static final name = obx.QueryStringProperty<LoanModel>(
    _entities[3].properties[1],
  );

  /// See [LoanModel.amount].
  static final amount = obx.QueryDoubleProperty<LoanModel>(
    _entities[3].properties[2],
  );

  /// See [LoanModel.lenderName].
  static final lenderName = obx.QueryStringProperty<LoanModel>(
    _entities[3].properties[3],
  );

  /// See [LoanModel.dayOfMonth].
  static final dayOfMonth = obx.QueryIntegerProperty<LoanModel>(
    _entities[3].properties[4],
  );

  /// See [LoanModel.startDate].
  static final startDate = obx.QueryDateProperty<LoanModel>(
    _entities[3].properties[5],
  );

  /// See [LoanModel.endDate].
  static final endDate = obx.QueryDateProperty<LoanModel>(
    _entities[3].properties[6],
  );

  /// See [LoanModel.accountId].
  static final accountId = obx.QueryIntegerProperty<LoanModel>(
    _entities[3].properties[7],
  );

  /// See [LoanModel.notes].
  static final notes = obx.QueryStringProperty<LoanModel>(
    _entities[3].properties[8],
  );

  /// See [LoanModel.interestRate].
  static final interestRate = obx.QueryDoubleProperty<LoanModel>(
    _entities[3].properties[9],
  );

  /// See [LoanModel.duration].
  static final duration = obx.QueryIntegerProperty<LoanModel>(
    _entities[3].properties[10],
  );

  /// See [LoanModel.insuranceValue].
  static final insuranceValue = obx.QueryDoubleProperty<LoanModel>(
    _entities[3].properties[11],
  );

  /// See [LoanModel.insuranceTypeId].
  static final insuranceTypeId = obx.QueryStringProperty<LoanModel>(
    _entities[3].properties[12],
  );

  /// See [LoanModel.repaymentTypeId].
  static final repaymentTypeId = obx.QueryStringProperty<LoanModel>(
    _entities[3].properties[13],
  );

  /// See [LoanModel.deferredMonths].
  static final deferredMonths = obx.QueryIntegerProperty<LoanModel>(
    _entities[3].properties[14],
  );

  /// See [LoanModel.insuranceCalculationModeId].
  static final insuranceCalculationModeId = obx.QueryStringProperty<LoanModel>(
    _entities[3].properties[15],
  );

  /// See [LoanModel.immediateFirstPayment].
  static final immediateFirstPayment = obx.QueryBooleanProperty<LoanModel>(
    _entities[3].properties[16],
  );

  /// See [LoanModel.deferralTypeId].
  static final deferralTypeId = obx.QueryStringProperty<LoanModel>(
    _entities[3].properties[17],
  );

  /// See [LoanModel.fees].
  static final fees = obx.QueryDoubleProperty<LoanModel>(
    _entities[3].properties[18],
  );

  /// See [LoanModel.hasIndemnityClause].
  static final hasIndemnityClause = obx.QueryBooleanProperty<LoanModel>(
    _entities[3].properties[19],
  );

  /// See [LoanModel.purposeId].
  static final purposeId = obx.QueryStringProperty<LoanModel>(
    _entities[3].properties[20],
  );
}

/// [RevenueModel] entity fields to define ObjectBox queries.
class RevenueModel_ {
  /// See [RevenueModel.id].
  static final id = obx.QueryIntegerProperty<RevenueModel>(
    _entities[4].properties[0],
  );

  /// See [RevenueModel.name].
  static final name = obx.QueryStringProperty<RevenueModel>(
    _entities[4].properties[1],
  );

  /// See [RevenueModel.accountId].
  static final accountId = obx.QueryIntegerProperty<RevenueModel>(
    _entities[4].properties[2],
  );

  /// See [RevenueModel.amount].
  static final amount = obx.QueryDoubleProperty<RevenueModel>(
    _entities[4].properties[3],
  );

  /// See [RevenueModel.startDate].
  static final startDate = obx.QueryDateProperty<RevenueModel>(
    _entities[4].properties[4],
  );

  /// See [RevenueModel.beneficiaryId].
  static final beneficiaryId = obx.QueryIntegerProperty<RevenueModel>(
    _entities[4].properties[5],
  );

  /// See [RevenueModel.frequency].
  static final frequency = obx.QueryStringProperty<RevenueModel>(
    _entities[4].properties[6],
  );

  /// See [RevenueModel.endDate].
  static final endDate = obx.QueryDateProperty<RevenueModel>(
    _entities[4].properties[7],
  );

  /// See [RevenueModel.parentId].
  static final parentId = obx.QueryIntegerProperty<RevenueModel>(
    _entities[4].properties[8],
  );

  /// See [RevenueModel.categorySlug].
  static final categorySlug = obx.QueryStringProperty<RevenueModel>(
    _entities[4].properties[9],
  );
}

/// [BeneficiaryModel] entity fields to define ObjectBox queries.
class BeneficiaryModel_ {
  /// See [BeneficiaryModel.id].
  static final id = obx.QueryIntegerProperty<BeneficiaryModel>(
    _entities[5].properties[0],
  );

  /// See [BeneficiaryModel.name].
  static final name = obx.QueryStringProperty<BeneficiaryModel>(
    _entities[5].properties[1],
  );

  /// See [BeneficiaryModel.color].
  static final color = obx.QueryIntegerProperty<BeneficiaryModel>(
    _entities[5].properties[2],
  );
}

/// [TransferModel] entity fields to define ObjectBox queries.
class TransferModel_ {
  /// See [TransferModel.id].
  static final id = obx.QueryIntegerProperty<TransferModel>(
    _entities[6].properties[0],
  );

  /// See [TransferModel.name].
  static final name = obx.QueryStringProperty<TransferModel>(
    _entities[6].properties[1],
  );

  /// See [TransferModel.amount].
  static final amount = obx.QueryDoubleProperty<TransferModel>(
    _entities[6].properties[2],
  );

  /// See [TransferModel.fromAccountId].
  static final fromAccountId = obx.QueryIntegerProperty<TransferModel>(
    _entities[6].properties[3],
  );

  /// See [TransferModel.toAccountId].
  static final toAccountId = obx.QueryIntegerProperty<TransferModel>(
    _entities[6].properties[4],
  );

  /// See [TransferModel.startDate].
  static final startDate = obx.QueryDateProperty<TransferModel>(
    _entities[6].properties[5],
  );

  /// See [TransferModel.frequency].
  static final frequency = obx.QueryStringProperty<TransferModel>(
    _entities[6].properties[6],
  );

  /// See [TransferModel.endDate].
  static final endDate = obx.QueryDateProperty<TransferModel>(
    _entities[6].properties[7],
  );

  /// See [TransferModel.parentId].
  static final parentId = obx.QueryIntegerProperty<TransferModel>(
    _entities[6].properties[8],
  );
}

/// [CategoryOverrideModel] entity fields to define ObjectBox queries.
class CategoryOverrideModel_ {
  /// See [CategoryOverrideModel.id].
  static final id = obx.QueryIntegerProperty<CategoryOverrideModel>(
    _entities[7].properties[0],
  );

  /// See [CategoryOverrideModel.slug].
  static final slug = obx.QueryStringProperty<CategoryOverrideModel>(
    _entities[7].properties[1],
  );

  /// See [CategoryOverrideModel.name].
  static final name = obx.QueryStringProperty<CategoryOverrideModel>(
    _entities[7].properties[2],
  );

  /// See [CategoryOverrideModel.icon].
  static final icon = obx.QueryStringProperty<CategoryOverrideModel>(
    _entities[7].properties[3],
  );

  /// See [CategoryOverrideModel.color].
  static final color = obx.QueryIntegerProperty<CategoryOverrideModel>(
    _entities[7].properties[4],
  );
}

/// [CategoryMemoryModel] entity fields to define ObjectBox queries.
class CategoryMemoryModel_ {
  /// See [CategoryMemoryModel.id].
  static final id = obx.QueryIntegerProperty<CategoryMemoryModel>(
    _entities[8].properties[0],
  );

  /// See [CategoryMemoryModel.key].
  static final key = obx.QueryStringProperty<CategoryMemoryModel>(
    _entities[8].properties[1],
  );

  /// See [CategoryMemoryModel.slug].
  static final slug = obx.QueryStringProperty<CategoryMemoryModel>(
    _entities[8].properties[2],
  );

  /// See [CategoryMemoryModel.corrections].
  static final corrections = obx.QueryIntegerProperty<CategoryMemoryModel>(
    _entities[8].properties[3],
  );

  /// See [CategoryMemoryModel.useMemory].
  static final useMemory = obx.QueryBooleanProperty<CategoryMemoryModel>(
    _entities[8].properties[4],
  );

  /// See [CategoryMemoryModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<CategoryMemoryModel>(
    _entities[8].properties[5],
  );
}

/// [LoanEventModel] entity fields to define ObjectBox queries.
class LoanEventModel_ {
  /// See [LoanEventModel.id].
  static final id = obx.QueryIntegerProperty<LoanEventModel>(
    _entities[9].properties[0],
  );

  /// See [LoanEventModel.loanId].
  static final loanId = obx.QueryIntegerProperty<LoanEventModel>(
    _entities[9].properties[1],
  );

  /// See [LoanEventModel.typeId].
  static final typeId = obx.QueryStringProperty<LoanEventModel>(
    _entities[9].properties[2],
  );

  /// See [LoanEventModel.date].
  static final date = obx.QueryDateProperty<LoanEventModel>(
    _entities[9].properties[3],
  );

  /// See [LoanEventModel.amount].
  static final amount = obx.QueryDoubleProperty<LoanEventModel>(
    _entities[9].properties[4],
  );

  /// See [LoanEventModel.reamortizationModeId].
  static final reamortizationModeId = obx.QueryStringProperty<LoanEventModel>(
    _entities[9].properties[5],
  );

  /// See [LoanEventModel.exemptionId].
  static final exemptionId = obx.QueryStringProperty<LoanEventModel>(
    _entities[9].properties[6],
  );
}

/// [TransactionEventModel] entity fields to define ObjectBox queries.
class TransactionEventModel_ {
  /// See [TransactionEventModel.id].
  static final id = obx.QueryIntegerProperty<TransactionEventModel>(
    _entities[10].properties[0],
  );

  /// See [TransactionEventModel.rootId].
  static final rootId = obx.QueryIntegerProperty<TransactionEventModel>(
    _entities[10].properties[1],
  );

  /// See [TransactionEventModel.transactionType].
  static final transactionType = obx.QueryStringProperty<TransactionEventModel>(
    _entities[10].properties[2],
  );

  /// See [TransactionEventModel.change].
  static final change = obx.QueryStringProperty<TransactionEventModel>(
    _entities[10].properties[3],
  );

  /// See [TransactionEventModel.previousValue].
  static final previousValue = obx.QueryStringProperty<TransactionEventModel>(
    _entities[10].properties[4],
  );

  /// See [TransactionEventModel.nextValue].
  static final nextValue = obx.QueryStringProperty<TransactionEventModel>(
    _entities[10].properties[5],
  );

  /// See [TransactionEventModel.at].
  static final at = obx.QueryDateProperty<TransactionEventModel>(
    _entities[10].properties[6],
  );
}
