import 'dart:convert';
import 'dart:io';

const String taxonomyPath = 'assets/categories.json';
const String labelsPath = 'lib/core/constants/quick_add_labels.dart';
const List<String> sections = ['expenses', 'income'];

void main(List<String> args) {
  final taxonomy =
      json.decode(File(taxonomyPath).readAsStringSync()) as Map<String, dynamic>;
  final slugs = _orderedSlugs(taxonomy);

  if (args.contains('--stdout')) {
    stdout.writeln(slugs.join('\n'));
    return;
  }

  File(labelsPath).writeAsStringSync(_renderLabels(slugs));
  stdout.writeln('${slugs.length} classes written to $labelsPath');
}

List<String> _orderedSlugs(Map<String, dynamic> taxonomy) {
  final slugs = <String>[];
  for (final section in sections) {
    final groups = taxonomy[section] as Map<String, dynamic>;
    for (final group in groups.entries) {
      final subcategories =
          (group.value as Map<String, dynamic>)['subcategories']
              as Map<String, dynamic>;
      for (final subcategory in subcategories.entries) {
        final body = subcategory.value as Map<String, dynamic>;
        if (body['deprecated'] == true) continue;
        slugs.add('${group.key}.${subcategory.key}');
      }
    }
  }
  return slugs;
}

String _renderLabels(List<String> slugs) {
  final entries = slugs.map((slug) => "    '$slug',").join('\n');
  return '''
// GENERATED BY tool/generate_taxonomy_labels.dart — DO NOT EDIT.
// Source: $taxonomyPath. Index order is the contract with the ONNX model.

abstract final class QuickAddLabels {
  static const List<String> types = ['expense', 'income'];

  static const List<String> categories = [
$entries
  ];

  static const List<String> recurrences = ['ponctuel', 'fixe'];
}
''';
}
