import 'dart:convert';
import 'dart:io';

const String taxonomyPath = 'assets/categories.json';
const String schemaPath =
    'android/app/src/main/kotlin/fr/jaetan/mybudget/nano/QuickAddOutput.kt';
const List<String> sections = ['expenses', 'income'];
const int maxAlternatives = 3;

void main(List<String> args) {
  final taxonomy =
      json.decode(File(taxonomyPath).readAsStringSync()) as Map<String, dynamic>;
  final slugs = selectableSlugs(taxonomy);

  if (args.contains('--stdout')) {
    stdout.writeln(slugs.join('\n'));
    return;
  }

  File(schemaPath)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(_renderSchema(slugs));
  stdout.writeln('${slugs.length} slugs written to $schemaPath');
}

List<String> selectableSlugs(Map<String, dynamic> taxonomy) {
  final slugs = <String>[];
  for (final section in sections) {
    final groups = taxonomy[section] as Map<String, dynamic>;
    for (final group in groups.entries) {
      final subcategories =
          (group.value as Map<String, dynamic>)['subcategories']
              as Map<String, dynamic>;
      for (final subcategory in subcategories.entries) {
        final body = subcategory.value as Map<String, dynamic>;
        if (body['deprecated'] == true) continue;
        if (body['alias_of'] != null) continue;
        slugs.add('${group.key}.${subcategory.key}');
      }
    }
  }
  return slugs;
}

String _renderSchema(List<String> slugs) {
  final entries = slugs.map((slug) => '            "$slug",').join('\n');
  return '''
// GENERATED BY tool/generate_nano_schema.dart — DO NOT EDIT.
// Source: $taxonomyPath. Mirrors PromptQuickAddEngine's selectable leaves.

package fr.jaetan.mybudget.nano

import com.google.mlkit.genai.schema.annotations.Generable
import com.google.mlkit.genai.schema.annotations.Guide

@Generable("Classement d'une saisie de dépense ou de revenu")
data class QuickAddOutput(
    @Guide(
        description = "La feuille de taxonomie la plus précise pour la saisie",
        enumValues = [
$entries
        ],
    )
    val categorySlug: String,
    @Guide(
        description =
            "Les feuilles les plus proches après celle retenue, sans la répéter",
        maxItems = $maxAlternatives,
    )
    val alternatives: List<String>,
    @Guide(
        description = "\\"fixe\\" pour ce qui revient chaque mois, sinon \\"ponctuel\\"",
        enumValues = ["ponctuel", "fixe"],
    )
    val recurrence: String,
    @Guide(description = "La saisie remise au propre, sans montant ni date")
    val name: String,
)
''';
}
