class BanksList {
  static const List<String> frenchBanks = [
    'BNP Paribas',
    'Société Générale',
    'Crédit Agricole',
    'LCL (Le Crédit Lyonnais)',
    'Caisse d\'Épargne',
    'Banque Populaire',
    'Crédit Mutuel',
    'La Banque Postale',
    'CIC (Crédit Industriel et Commercial)',
    'HSBC France',
    'Crédit du Nord',
    'Bred Banque Populaire',
    'Banque Palatine',
    'Arkéa',

    'Boursorama Banque (BoursoBank)',
    'Hello Bank!',
    'Fortuneo',
    'Monabanq',
    'BforBank',
    'Revolut',
    'N26',
    'Nickel',
    'Orange Bank',
    'Ma French Bank',
    'Lydia',
    'Qonto',
    'Shine',
    'Bunq',
    'Pixpay',
    'Kard',
    'Vybe',
    'Helios',
    'Green-Got',
    'OnlyOne',
    'Canara',

    'AXA Banque',
    'Allianz Banque',
    'Groupama Banque',
    'Macif',
    'Matmut',
    'Carrefour Banque',
    'Oney',
    'Floa Bank',

    'Banque Courtois',
    'Banque Kolb',
    'Banque Laydernier',
    'Banque Nuger',
    'Banque Rhône-Alpes',
    'Banque Tarneaud',
    'Société Marseillaise de Crédit',
    'Banque Transatlantique',
    'Rothschild Martin Maurel',
    'Milleis Banque',
    'Delubac & Cie',
    'Banque Wormser Frères',
  ];
}
