abstract final class QuickAddLabels {
  static const List<String> types = ['expense', 'income'];

  static const List<String> categories = [
    'alimentation.supermarché',
    'alimentation.marché',
    'alimentation.épicerie',
    'alimentation.boulangerie',
    'restauration.restaurant',
    'restauration.fast-food/friterie',
    'restauration.bar/apéro',
    'restauration.café',
    'restauration.livraison',
    'transport.essence',
    'transport.transport en commun',
    'transport.taxi/VTC',
    'transport.parking',
    'transport.péage',
    'transport.entretien véhicule',
    'logement.loyer',
    'logement.charges',
    'logement.énergie',
    'logement.eau',
    'logement.télécom/internet',
    'logement.assurance',
    'sante_beaute.médecin',
    'sante_beaute.pharmacie',
    'sante_beaute.mutuelle',
    'sante_beaute.coiffeur',
    'sante_beaute.esthétique',
    'loisirs.cinéma/sorties',
    'loisirs.jeux vidéo',
    'loisirs.sport',
    'loisirs.manga/livres',
    'loisirs.streaming',
    'loisirs.musique',
    'shopping.vêtements',
    'shopping.électronique',
    'shopping.mobilier/déco',
    'finance_taxes.retrait DAB',
    'finance_taxes.frais bancaires',
    'finance_taxes.impôts/taxes',
    'finance_taxes.amendes',
    'education.scolarité',
    'education.fournitures',
    'education.formation',
    'divers.cadeau offert',
    'divers.vétérinaire/animaux',
    "divers.tabac/jeux d'argent",
    'divers.autre',
    'salaire.salaire net',
    'salaire.prime',
    'salaire.revenu freelance',
    'transfert.virement reçu',
    'transfert.remboursement santé',
    'transfert.remboursement ami',
    'exceptionnel.vente occasion',
    'exceptionnel.don reçu',
    'exceptionnel.intérêts',
  ];

  static const List<String> recurrences = ['ponctuel', 'fixe'];
}
