name: Run Linter

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.1'
          cache: true


      - name: Install dependencies
        run: flutter pub get

      - name: Install frosted_ui dependencies
        run: flutter pub get
        working-directory: frosted_ui

      - name: Install frosted_ui example dependencies
        run: flutter pub get
        working-directory: frosted_ui/example

      - name: Run linter
        run: flutter analyze
