name: Create Release

on:
  push:
    branches:
      - main
      - master

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Setup key.properties
        run: |
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Decode Keystore
        run: |
          mkdir -p android/app/keystore
          echo ${{ secrets.KEYSTORE_BASE64 }} | base64 -d > android/app/keystore/mybudget_key.jks



      - name: Flutter pub get
        run: flutter pub get

      - name: Build apk
        run: flutter build apk --flavor prod --release --no-tree-shake-icons

      - name: Extract version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed -e 's/version: //' -e 's/+.*//')
          BUILD=$(grep 'version:' pubspec.yaml | sed -e 's/version: //' -e 's/.*+//')
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=build::$BUILD"
      
      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v${{ steps.get_version.outputs.version }} -m "Release v${{ steps.get_version.outputs.version }}"
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-prod-release.apk build/app/outputs/flutter-apk/mybudget-v${{ steps.get_version.outputs.version }}+${{ steps.get_version.outputs.build }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: MyBudget v${{ steps.get_version.outputs.version }}
          body_path: release_notes.md
          generate_release_notes: false
          draft: false
          prerelease: false
          files: |
            build/app/outputs/flutter-apk/mybudget-v${{ steps.get_version.outputs.version }}+${{ steps.get_version.outputs.build }}.apk
